--liquibase formatted sql

--changeset migration:V001_create_reference_catalog labels:1 splitStatements:false
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
    CREATE TYPE order_status AS ENUM (
      'pending',
      'paid',
      'assembling',
      'ready_for_pickup',
      'picked_up',
      'canceled',
      'expired'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'purchase_order_status') THEN
    CREATE TYPE purchase_order_status AS ENUM (
      'waiting_approval',
      'drafting',
      'partially_delivered',
      'delivered',
      'received',
      'canceled'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'employee_role') THEN
    CREATE TYPE employee_role AS ENUM (
      'manager',
      'warehouse',
      'picker',
      'accountant',
      'support'
    );
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS countries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  iso_code CHAR(2) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS beer_styles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT
);

CREATE TABLE IF NOT EXISTS package_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL UNIQUE
);

--rollback DROP TABLE IF EXISTS package_types CASCADE;
--rollback DROP TABLE IF EXISTS beer_styles CASCADE;
--rollback DROP TABLE IF EXISTS countries CASCADE;
--rollback DROP TYPE IF EXISTS employee_role;
--rollback DROP TYPE IF EXISTS purchase_order_status;
--rollback DROP TYPE IF EXISTS order_status;
