--liquibase formatted sql

--changeset migration:V002_create_product_catalog labels:2 splitStatements:false
CREATE TABLE IF NOT EXISTS breweries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id BIGINT NOT NULL REFERENCES countries (id),
  name VARCHAR(150) NOT NULL,
  website_url VARCHAR(255),
  founded_year INT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (country_id, name)
);

CREATE TABLE IF NOT EXISTS beers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brewery_id BIGINT NOT NULL REFERENCES breweries (id),
  style_id BIGINT NOT NULL REFERENCES beer_styles (id),
  name VARCHAR(150) NOT NULL,
  description TEXT,
  abv NUMERIC(4, 2) NOT NULL CHECK (abv >= 0 AND abv <= 100),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (brewery_id, name)
);

CREATE TABLE IF NOT EXISTS product_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beer_id BIGINT NOT NULL REFERENCES beers (id),
  package_type_id BIGINT NOT NULL REFERENCES package_types (id),
  sku VARCHAR(64) NOT NULL UNIQUE,
  volume_ml INT NOT NULL CHECK (volume_ml > 0),
  unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (beer_id, package_type_id, volume_ml)
);

--rollback DROP TABLE IF EXISTS product_variants CASCADE;
--rollback DROP TABLE IF EXISTS beers CASCADE;
--rollback DROP TABLE IF EXISTS breweries CASCADE;
