--liquibase formatted sql

--changeset migration:V003_create_supply_chain labels:3 splitStatements:false
CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id BIGINT REFERENCES countries (id),
  name VARCHAR(150) NOT NULL UNIQUE,
  contact_email VARCHAR(255),
  contact_phone VARCHAR(40),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS warehouses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id BIGINT NOT NULL REFERENCES countries (id),
  name VARCHAR(120) NOT NULL UNIQUE,
  address_line VARCHAR(255) NOT NULL,
  city VARCHAR(120) NOT NULL,
  postal_code VARCHAR(20),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pickup_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  warehouse_id BIGINT NOT NULL REFERENCES warehouses (id),
  name VARCHAR(120) NOT NULL,
  city VARCHAR(120) NOT NULL,
  address_line VARCHAR(255) NOT NULL,
  postal_code VARCHAR(20),
  working_hours VARCHAR(200),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (warehouse_id, name)
);

CREATE TABLE IF NOT EXISTS purchase_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id BIGINT NOT NULL REFERENCES suppliers (id),
  warehouse_id BIGINT NOT NULL REFERENCES warehouses (id),
  status purchase_order_status NOT NULL DEFAULT 'waiting_approval',
  ordered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expected_at TIMESTAMPTZ,
  received_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS purchase_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id BIGINT NOT NULL REFERENCES purchase_orders (id),
  variant_id BIGINT NOT NULL REFERENCES product_variants (id),
  quantity INT NOT NULL CHECK (quantity > 0),
  unit_cost NUMERIC(12, 2) NOT NULL CHECK (unit_cost >= 0),
  UNIQUE (purchase_order_id, variant_id)
);

CREATE TABLE IF NOT EXISTS inventory_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id BIGINT NOT NULL REFERENCES product_variants (id),
  warehouse_id BIGINT NOT NULL REFERENCES warehouses (id),
  purchase_order_item_id BIGINT REFERENCES purchase_order_items (id),
  lot_code VARCHAR(60) NOT NULL,
  quantity_on_hand INT NOT NULL CHECK (quantity_on_hand >= 0),
  wholesale_cost NUMERIC(12, 2) NOT NULL CHECK (wholesale_cost >= 0),
  produced_on DATE,
  expires_on DATE,
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (warehouse_id, variant_id, lot_code)
);

--rollback DROP TABLE IF EXISTS inventory_batches CASCADE;
--rollback DROP TABLE IF EXISTS purchase_order_items CASCADE;
--rollback DROP TABLE IF EXISTS purchase_orders CASCADE;
--rollback DROP TABLE IF EXISTS pickup_points CASCADE;
--rollback DROP TABLE IF EXISTS warehouses CASCADE;
--rollback DROP TABLE IF EXISTS suppliers CASCADE;
