--liquibase formatted sql

--changeset migration:V004_create_customer_flow labels:4 splitStatements:false
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(40),
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  birth_date DATE,
  registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS carts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL UNIQUE REFERENCES customers (id),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id BIGINT NOT NULL REFERENCES carts (id) ON DELETE CASCADE,
  variant_id BIGINT NOT NULL REFERENCES product_variants (id),
  quantity INT NOT NULL CHECK (quantity > 0),
  added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (cart_id, variant_id)
);

CREATE TABLE IF NOT EXISTS customer_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers (id),
  pickup_point_id BIGINT NOT NULL REFERENCES pickup_points (id),
  status order_status NOT NULL DEFAULT 'pending',
  subtotal_amount NUMERIC(12, 2) NOT NULL CHECK (subtotal_amount >= 0),
  discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
  total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0),
  pickup_code VARCHAR(20) NOT NULL UNIQUE,
  placed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ready_for_pickup_at TIMESTAMPTZ,
  pickup_expires_at TIMESTAMPTZ,
  picked_up_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES customer_orders (id) ON DELETE CASCADE,
  variant_id BIGINT NOT NULL REFERENCES product_variants (id),
  batch_id BIGINT REFERENCES inventory_batches (id),
  quantity INT NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
  line_discount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (line_discount >= 0),
  UNIQUE (order_id, variant_id)
);

--rollback DROP TABLE IF EXISTS order_items CASCADE;
--rollback DROP TABLE IF EXISTS customer_orders CASCADE;
--rollback DROP TABLE IF EXISTS cart_items CASCADE;
--rollback DROP TABLE IF EXISTS carts CASCADE;
--rollback DROP TABLE IF EXISTS customers CASCADE;
