--liquibase formatted sql

--changeset migration:V005_create_staff_history_reviews_tables labels:5 splitStatements:false
CREATE TABLE IF NOT EXISTS employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  role employee_role NOT NULL,
  hired_at DATE NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS order_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES customer_orders (id) ON DELETE CASCADE,
  changed_by_employee_id BIGINT REFERENCES employees (id),
  from_status order_status,
  to_status order_status NOT NULL,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
  beer_id BIGINT NOT NULL REFERENCES beers (id),
  rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (customer_id, beer_id)
);

--rollback DROP TABLE IF EXISTS reviews CASCADE;
--rollback DROP TABLE IF EXISTS order_status_history CASCADE;
--rollback DROP TABLE IF EXISTS employees CASCADE;
