--liquibase formatted sql

--changeset migration:V006_add_product_views labels:6 splitStatements:false
CREATE TABLE IF NOT EXISTS product_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id BIGINT NOT NULL REFERENCES product_variants (id),
  customer_id BIGINT REFERENCES customers (id),
  viewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

--rollback DROP TABLE IF EXISTS product_views CASCADE;