--liquibase formatted sql
--changeset migration:V007_add_order_audit_trigger labels:7 splitStatements:false
CREATE TABLE order_audit_log (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id  BIGINT,
    action    TEXT,
    snapshot  JSONB,
    logged_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION fn_log_order() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO order_audit_log(order_id, action, snapshot)
    VALUES (NEW.id, TG_OP, row_to_json(NEW)::jsonb);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_order_audit
AFTER INSERT OR UPDATE ON customer_orders
FOR EACH ROW EXECUTE FUNCTION fn_log_order();
--rollback DROP TRIGGER IF EXISTS trg_order_audit ON customer_orders;
--rollback DROP FUNCTION IF EXISTS fn_log_order();
--rollback DROP TABLE IF EXISTS order_audit_log;
