#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 -U postgres <<-EOSQL
    CREATE USER "${POSTGRES_USER}" WITH PASSWORD '${POSTGRES_PASSWORD}' CREATEDB;
    CREATE DATABASE "${POSTGRES_DB}" OWNER "${POSTGRES_USER}";
    CREATE USER "${PG_EXPORTER_USER}" WITH PASSWORD '${PG_EXPORTER_PASSWORD}';
    GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${PG_EXPORTER_USER}";
    GRANT pg_monitor TO "${PG_EXPORTER_USER}";
    CREATE USER debezium_user WITH REPLICATION LOGIN PASSWORD 'debezium_password';
    GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO debezium_user;
EOSQL

psql -v ON_ERROR_STOP=1 -U postgres -d "${POSTGRES_DB}" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
EOSQL